"""
context_exception.py

"""

class ContextException(Exception):
	"""
	"""

	def __init__(self):
		"""
		"""

		pass